// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SdrUIClient is the client API for SdrUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdrUIClient interface {
	// ListAntennaSpecs returns a list of Antenna(s) that can be started through the UI.
	ListAntennaSpecs(ctx context.Context, in *ListAntennaSpecsRequest, opts ...grpc.CallOption) (SdrUI_ListAntennaSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type sdrUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSdrUIClient(cc grpc.ClientConnInterface) SdrUIClient {
	return &sdrUIClient{cc}
}

func (c *sdrUIClient) ListAntennaSpecs(ctx context.Context, in *ListAntennaSpecsRequest, opts ...grpc.CallOption) (SdrUI_ListAntennaSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdrUI_ServiceDesc.Streams[0], "/v1.SdrUI/ListAntennaSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdrUIListAntennaSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SdrUI_ListAntennaSpecsClient interface {
	Recv() (*ListAntennaSpecsResponse, error)
	grpc.ClientStream
}

type sdrUIListAntennaSpecsClient struct {
	grpc.ClientStream
}

func (x *sdrUIListAntennaSpecsClient) Recv() (*ListAntennaSpecsResponse, error) {
	m := new(ListAntennaSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdrUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SdrUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdrUIServer is the server API for SdrUI service.
// All implementations must embed UnimplementedSdrUIServer
// for forward compatibility
type SdrUIServer interface {
	// ListAntennaSpecs returns a list of Antenna(s) that can be started through the UI.
	ListAntennaSpecs(*ListAntennaSpecsRequest, SdrUI_ListAntennaSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSdrUIServer()
}

// UnimplementedSdrUIServer must be embedded to have forward compatible implementations.
type UnimplementedSdrUIServer struct {
}

func (UnimplementedSdrUIServer) ListAntennaSpecs(*ListAntennaSpecsRequest, SdrUI_ListAntennaSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAntennaSpecs not implemented")
}
func (UnimplementedSdrUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSdrUIServer) mustEmbedUnimplementedSdrUIServer() {}

// UnsafeSdrUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdrUIServer will
// result in compilation errors.
type UnsafeSdrUIServer interface {
	mustEmbedUnimplementedSdrUIServer()
}

func RegisterSdrUIServer(s grpc.ServiceRegistrar, srv SdrUIServer) {
	s.RegisterService(&SdrUI_ServiceDesc, srv)
}

func _SdrUI_ListAntennaSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListAntennaSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SdrUIServer).ListAntennaSpecs(m, &sdrUIListAntennaSpecsServer{stream})
}

type SdrUI_ListAntennaSpecsServer interface {
	Send(*ListAntennaSpecsResponse) error
	grpc.ServerStream
}

type sdrUIListAntennaSpecsServer struct {
	grpc.ServerStream
}

func (x *sdrUIListAntennaSpecsServer) Send(m *ListAntennaSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SdrUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdrUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdrUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdrUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SdrUI_ServiceDesc is the grpc.ServiceDesc for SdrUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SdrUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SdrUI",
	HandlerType: (*SdrUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SdrUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAntennaSpecs",
			Handler:       _SdrUI_ListAntennaSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdr-ui.proto",
}
