// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SdrServiceClient is the client API for SdrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SdrServiceClient interface {
	// StartLocalAntenna starts an Antenna on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the sdr/config.yaml
	//   3. all bytes constituting the Antenna YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalAntenna(ctx context.Context, opts ...grpc.CallOption) (SdrService_StartLocalAntennaClient, error)
	// StartFromPreviousAntenna starts a new Antenna based on a previous one.
	// If the previous Antenna does not have the can-replay condition set this call will result in an error.
	StartFromPreviousAntenna(ctx context.Context, in *StartFromPreviousAntennaRequest, opts ...grpc.CallOption) (*StartAntennaResponse, error)
	// StartAntennaRequest starts a new Antenna based on its specification.
	StartAntenna(ctx context.Context, in *StartAntennaRequest, opts ...grpc.CallOption) (*StartAntennaResponse, error)
	// Searches for Antenna(s) known to this instance
	ListAntennas(ctx context.Context, in *ListAntennasRequest, opts ...grpc.CallOption) (*ListAntennasResponse, error)
	// Subscribe listens to new Antenna(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SdrService_SubscribeClient, error)
	// GetAntenna retrieves details of a single Antenna
	GetAntenna(ctx context.Context, in *GetAntennaRequest, opts ...grpc.CallOption) (*GetAntennaResponse, error)
	// Listen listens to Antenna updates and log output of a running Antenna
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (SdrService_ListenClient, error)
	// StopAntenna stops a currently running Antenna
	StopAntenna(ctx context.Context, in *StopAntennaRequest, opts ...grpc.CallOption) (*StopAntennaResponse, error)
}

type sdrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSdrServiceClient(cc grpc.ClientConnInterface) SdrServiceClient {
	return &sdrServiceClient{cc}
}

func (c *sdrServiceClient) StartLocalAntenna(ctx context.Context, opts ...grpc.CallOption) (SdrService_StartLocalAntennaClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdrService_ServiceDesc.Streams[0], "/v1.SdrService/StartLocalAntenna", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdrServiceStartLocalAntennaClient{stream}
	return x, nil
}

type SdrService_StartLocalAntennaClient interface {
	Send(*StartLocalAntennaRequest) error
	CloseAndRecv() (*StartAntennaResponse, error)
	grpc.ClientStream
}

type sdrServiceStartLocalAntennaClient struct {
	grpc.ClientStream
}

func (x *sdrServiceStartLocalAntennaClient) Send(m *StartLocalAntennaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sdrServiceStartLocalAntennaClient) CloseAndRecv() (*StartAntennaResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartAntennaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdrServiceClient) StartFromPreviousAntenna(ctx context.Context, in *StartFromPreviousAntennaRequest, opts ...grpc.CallOption) (*StartAntennaResponse, error) {
	out := new(StartAntennaResponse)
	err := c.cc.Invoke(ctx, "/v1.SdrService/StartFromPreviousAntenna", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdrServiceClient) StartAntenna(ctx context.Context, in *StartAntennaRequest, opts ...grpc.CallOption) (*StartAntennaResponse, error) {
	out := new(StartAntennaResponse)
	err := c.cc.Invoke(ctx, "/v1.SdrService/StartAntenna", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdrServiceClient) ListAntennas(ctx context.Context, in *ListAntennasRequest, opts ...grpc.CallOption) (*ListAntennasResponse, error) {
	out := new(ListAntennasResponse)
	err := c.cc.Invoke(ctx, "/v1.SdrService/ListAntennas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdrServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SdrService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdrService_ServiceDesc.Streams[1], "/v1.SdrService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdrServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SdrService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type sdrServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *sdrServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdrServiceClient) GetAntenna(ctx context.Context, in *GetAntennaRequest, opts ...grpc.CallOption) (*GetAntennaResponse, error) {
	out := new(GetAntennaResponse)
	err := c.cc.Invoke(ctx, "/v1.SdrService/GetAntenna", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sdrServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (SdrService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &SdrService_ServiceDesc.Streams[2], "/v1.SdrService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &sdrServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SdrService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type sdrServiceListenClient struct {
	grpc.ClientStream
}

func (x *sdrServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sdrServiceClient) StopAntenna(ctx context.Context, in *StopAntennaRequest, opts ...grpc.CallOption) (*StopAntennaResponse, error) {
	out := new(StopAntennaResponse)
	err := c.cc.Invoke(ctx, "/v1.SdrService/StopAntenna", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SdrServiceServer is the server API for SdrService service.
// All implementations must embed UnimplementedSdrServiceServer
// for forward compatibility
type SdrServiceServer interface {
	// StartLocalAntenna starts an Antenna on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the sdr/config.yaml
	//   3. all bytes constituting the Antenna YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalAntenna(SdrService_StartLocalAntennaServer) error
	// StartFromPreviousAntenna starts a new Antenna based on a previous one.
	// If the previous Antenna does not have the can-replay condition set this call will result in an error.
	StartFromPreviousAntenna(context.Context, *StartFromPreviousAntennaRequest) (*StartAntennaResponse, error)
	// StartAntennaRequest starts a new Antenna based on its specification.
	StartAntenna(context.Context, *StartAntennaRequest) (*StartAntennaResponse, error)
	// Searches for Antenna(s) known to this instance
	ListAntennas(context.Context, *ListAntennasRequest) (*ListAntennasResponse, error)
	// Subscribe listens to new Antenna(s) updates
	Subscribe(*SubscribeRequest, SdrService_SubscribeServer) error
	// GetAntenna retrieves details of a single Antenna
	GetAntenna(context.Context, *GetAntennaRequest) (*GetAntennaResponse, error)
	// Listen listens to Antenna updates and log output of a running Antenna
	Listen(*ListenRequest, SdrService_ListenServer) error
	// StopAntenna stops a currently running Antenna
	StopAntenna(context.Context, *StopAntennaRequest) (*StopAntennaResponse, error)
	mustEmbedUnimplementedSdrServiceServer()
}

// UnimplementedSdrServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSdrServiceServer struct {
}

func (UnimplementedSdrServiceServer) StartLocalAntenna(SdrService_StartLocalAntennaServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalAntenna not implemented")
}
func (UnimplementedSdrServiceServer) StartFromPreviousAntenna(context.Context, *StartFromPreviousAntennaRequest) (*StartAntennaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousAntenna not implemented")
}
func (UnimplementedSdrServiceServer) StartAntenna(context.Context, *StartAntennaRequest) (*StartAntennaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAntenna not implemented")
}
func (UnimplementedSdrServiceServer) ListAntennas(context.Context, *ListAntennasRequest) (*ListAntennasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAntennas not implemented")
}
func (UnimplementedSdrServiceServer) Subscribe(*SubscribeRequest, SdrService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedSdrServiceServer) GetAntenna(context.Context, *GetAntennaRequest) (*GetAntennaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAntenna not implemented")
}
func (UnimplementedSdrServiceServer) Listen(*ListenRequest, SdrService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedSdrServiceServer) StopAntenna(context.Context, *StopAntennaRequest) (*StopAntennaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAntenna not implemented")
}
func (UnimplementedSdrServiceServer) mustEmbedUnimplementedSdrServiceServer() {}

// UnsafeSdrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SdrServiceServer will
// result in compilation errors.
type UnsafeSdrServiceServer interface {
	mustEmbedUnimplementedSdrServiceServer()
}

func RegisterSdrServiceServer(s grpc.ServiceRegistrar, srv SdrServiceServer) {
	s.RegisterService(&SdrService_ServiceDesc, srv)
}

func _SdrService_StartLocalAntenna_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SdrServiceServer).StartLocalAntenna(&sdrServiceStartLocalAntennaServer{stream})
}

type SdrService_StartLocalAntennaServer interface {
	SendAndClose(*StartAntennaResponse) error
	Recv() (*StartLocalAntennaRequest, error)
	grpc.ServerStream
}

type sdrServiceStartLocalAntennaServer struct {
	grpc.ServerStream
}

func (x *sdrServiceStartLocalAntennaServer) SendAndClose(m *StartAntennaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sdrServiceStartLocalAntennaServer) Recv() (*StartLocalAntennaRequest, error) {
	m := new(StartLocalAntennaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SdrService_StartFromPreviousAntenna_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousAntennaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdrServiceServer).StartFromPreviousAntenna(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdrService/StartFromPreviousAntenna",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdrServiceServer).StartFromPreviousAntenna(ctx, req.(*StartFromPreviousAntennaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdrService_StartAntenna_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAntennaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdrServiceServer).StartAntenna(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdrService/StartAntenna",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdrServiceServer).StartAntenna(ctx, req.(*StartAntennaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdrService_ListAntennas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAntennasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdrServiceServer).ListAntennas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdrService/ListAntennas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdrServiceServer).ListAntennas(ctx, req.(*ListAntennasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdrService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SdrServiceServer).Subscribe(m, &sdrServiceSubscribeServer{stream})
}

type SdrService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type sdrServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *sdrServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SdrService_GetAntenna_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAntennaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdrServiceServer).GetAntenna(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdrService/GetAntenna",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdrServiceServer).GetAntenna(ctx, req.(*GetAntennaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SdrService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SdrServiceServer).Listen(m, &sdrServiceListenServer{stream})
}

type SdrService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type sdrServiceListenServer struct {
	grpc.ServerStream
}

func (x *sdrServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SdrService_StopAntenna_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAntennaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SdrServiceServer).StopAntenna(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SdrService/StopAntenna",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SdrServiceServer).StopAntenna(ctx, req.(*StopAntennaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SdrService_ServiceDesc is the grpc.ServiceDesc for SdrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SdrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SdrService",
	HandlerType: (*SdrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousAntenna",
			Handler:    _SdrService_StartFromPreviousAntenna_Handler,
		},
		{
			MethodName: "StartAntenna",
			Handler:    _SdrService_StartAntenna_Handler,
		},
		{
			MethodName: "ListAntennas",
			Handler:    _SdrService_ListAntennas_Handler,
		},
		{
			MethodName: "GetAntenna",
			Handler:    _SdrService_GetAntenna_Handler,
		},
		{
			MethodName: "StopAntenna",
			Handler:    _SdrService_StopAntenna_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalAntenna",
			Handler:       _SdrService_StartLocalAntenna_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _SdrService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _SdrService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdr.proto",
}
